name: Run ESLINT 
on: push
jobs:
      eslint:
        runs-on: ubuntu-latest
        steps:
        - name: Install dependencies
          run: npm install
        - name: Run eslint
          run: npx eslint
