name: Run ESLINT 
on: push
jobs:
      eslint:
        runs-on: ubuntu-latest
        steps:
        - name: Install dependencies
          run: npm init -y
        - name: Run eslint
          run: npm i eslint
        - name: Run code
          run: node index.js